import {
  getAddonDetailsRequest,
  getAddonDetailsResponse,
  getAddonsRequest,
  getAddonsResponse,
} from "./addons";
import {
  getAlbumDetailsRequest,
  getAlbumDetailsResponse,
  getAlbumsRequest,
  getAlbumsResponse,
  getArtistDetailsRequest,
  getArtistDetailsResponse,
  getArtistsRequest,
  getArtistsResponse,
  getGenresRequest as getAudioGenresRequest,
  getGenresResponse as getAudioGenresResponse,
  getRecentlyAddedAlbumsRequest,
  getRecentlyAddedAlbumsResponse,
  getSongDetailsRequest,
  getSongDetailsResponse,
  getSongsRequest,
  getSongsResponse,
} from "./audio";
import {
  applicationOnVolumeChange,
  audioLibraryOnCleanFinished,
  audioLibraryOnCleanStarted,
  audioLibraryOnExport,
  audioLibraryOnRemove,
  audioLibraryOnScanFinished,
  audioLibraryOnScanStarted,
  audioLibraryOnUpdate,
  guiOnDPMSActivated,
  guiOnDPMSDeactivated,
  guiOnScreensaverActivated,
  guiOnScreensaverDeactivated,
  inputOnInputFinished,
  inputOnInputRequested,
  playerOnAVChange,
  playerOnPause,
  playerOnPlay,
  playerOnPropertyChanged,
  playerOnResume,
  playerOnSeek,
  playerOnSpeedChanged,
  playerOnStop,
  playlistOnAdd,
  playlistOnClear,
  playlistOnRemove,
  systemOnLowBattery,
  systemOnQuit,
  systemOnRestart,
  systemOnSleep,
  systemOnWake,
  videoLibraryOnCleanFinished,
  videoLibraryOnCleanStarted,
  videoLibraryOnExport,
  videoLibraryOnRefresh,
  videoLibraryOnRemove,
  videoLibraryOnScanFinished,
  videoLibraryOnScanStarted,
  videoLibraryOnUpdate,
} from "./notifications";
import {
  getActivePlayersRequest,
  getActivePlayersResponse,
  getItemRequest,
  getItemResponse,
  getPlayersRequest,
  getPlayersResponse,
  getPropertiesRequest,
  getPropertiesResponse,
  playPauseRequest,
  playPauseResponse,
  stopRequest,
  stopResponse,
} from "./player";
import {
  getCurrentProfileRequest,
  getCurrentProfileResponse,
  getProfilesRequest,
  getProfilesResponse,
} from "./profiles";
import {
  getEpisodeDetailsRequest,
  getEpisodeDetailsResponse,
  getEpisodesRequest,
  getEpisodesResponse,
  getInProgressTVShowsRequest,
  getInProgressTVShowsResponse,
  getMovieDetailsRequest,
  getMovieDetailsResponse,
  getMovieSetDetailsRequest,
  getMovieSetDetailsResponse,
  getMovieSetsRequest,
  getMovieSetsResponse,
  getMoviesRequest,
  getMoviesResponse,
  getRecentlyAddedEpisodesRequest,
  getRecentlyAddedEpisodesResponse,
  getRecentlyAddedMoviesRequest,
  getRecentlyAddedMoviesResponse,
  getSeasonDetailsRequest,
  getSeasonDetailsResponse,
  getSeasonsRequest,
  getSeasonsResponse,
  getTVShowDetailsRequest,
  getTVShowDetailsResponse,
  getTVShowsRequest,
  getTVShowsResponse,
  getGenresRequest as getVideoGenresRequest,
  getGenresResponse as getVideoGenresResponse,
} from "./video";

export const requestResponseMap = {
  "Addons.GetAddonDetails": {
    request: getAddonDetailsRequest,
    response: getAddonDetailsResponse,
  },
  "Addons.GetAddons": {
    request: getAddonsRequest,
    response: getAddonsResponse,
  },
  "Application.GetProperties": {
    request: getPropertiesRequest,
    response: getPropertiesResponse,
  },
  "AudioLibrary.GetAlbumDetails": {
    request: getAlbumDetailsRequest,
    response: getAlbumDetailsResponse,
  },
  "AudioLibrary.GetAlbums": {
    request: getAlbumsRequest,
    response: getAlbumsResponse,
  },
  "AudioLibrary.GetArtistDetails": {
    request: getArtistDetailsRequest,
    response: getArtistDetailsResponse,
  },
  "AudioLibrary.GetArtists": {
    request: getArtistsRequest,
    response: getArtistsResponse,
  },
  "AudioLibrary.GetGenres": {
    request: getAudioGenresRequest,
    response: getAudioGenresResponse,
  },
  "AudioLibrary.GetRecentlyAddedAlbums": {
    request: getRecentlyAddedAlbumsRequest,
    response: getRecentlyAddedAlbumsResponse,
  },
  "AudioLibrary.GetSongDetails": {
    request: getSongDetailsRequest,
    response: getSongDetailsResponse,
  },
  "AudioLibrary.GetSongs": {
    request: getSongsRequest,
    response: getSongsResponse,
  },
  "Player.GetActivePlayers": {
    request: getActivePlayersRequest,
    response: getActivePlayersResponse,
  },
  "Player.GetItem": { request: getItemRequest, response: getItemResponse },
  "Player.GetPlayers": {
    request: getPlayersRequest,
    response: getPlayersResponse,
  },
  "Player.GetProperties": {
    request: getPropertiesRequest,
    response: getPropertiesResponse,
  },
  "Player.PlayPause": {
    request: playPauseRequest,
    response: playPauseResponse,
  },
  "Player.Stop": { request: stopRequest, response: stopResponse },
  "Profiles.GetCurrentProfile": {
    request: getCurrentProfileRequest,
    response: getCurrentProfileResponse,
  },
  "Profiles.GetProfiles": {
    request: getProfilesRequest,
    response: getProfilesResponse,
  },
  "VideoLibrary.GetEpisodeDetails": {
    request: getEpisodeDetailsRequest,
    response: getEpisodeDetailsResponse,
  },
  "VideoLibrary.GetEpisodes": {
    request: getEpisodesRequest,
    response: getEpisodesResponse,
  },
  "VideoLibrary.GetGenres": {
    request: getVideoGenresRequest,
    response: getVideoGenresResponse,
  },
  "VideoLibrary.GetInProgressTVShows": {
    request: getInProgressTVShowsRequest,
    response: getInProgressTVShowsResponse,
  },
  "VideoLibrary.GetMovieDetails": {
    request: getMovieDetailsRequest,
    response: getMovieDetailsResponse,
  },
  "VideoLibrary.GetMovieSetDetails": {
    request: getMovieSetDetailsRequest,
    response: getMovieSetDetailsResponse,
  },
  "VideoLibrary.GetMovieSets": {
    request: getMovieSetsRequest,
    response: getMovieSetsResponse,
  },
  "VideoLibrary.GetMovies": {
    request: getMoviesRequest,
    response: getMoviesResponse,
  },
  "VideoLibrary.GetRecentlyAddedEpisodes": {
    request: getRecentlyAddedEpisodesRequest,
    response: getRecentlyAddedEpisodesResponse,
  },
  "VideoLibrary.GetRecentlyAddedMovies": {
    request: getRecentlyAddedMoviesRequest,
    response: getRecentlyAddedMoviesResponse,
  },
  "VideoLibrary.GetSeasonDetails": {
    request: getSeasonDetailsRequest,
    response: getSeasonDetailsResponse,
  },
  "VideoLibrary.GetSeasons": {
    request: getSeasonsRequest,
    response: getSeasonsResponse,
  },
  "VideoLibrary.GetTVShowDetails": {
    request: getTVShowDetailsRequest,
    response: getTVShowDetailsResponse,
  },
  "VideoLibrary.GetTVShows": {
    request: getTVShowsRequest,
    response: getTVShowsResponse,
  },
};

export const notificationMap = {
  "Application.OnVolumeChange": applicationOnVolumeChange,
  "AudioLibrary.OnCleanFinished": audioLibraryOnCleanFinished,
  "AudioLibrary.OnCleanStarted": audioLibraryOnCleanStarted,
  "AudioLibrary.OnExport": audioLibraryOnExport,
  "AudioLibrary.OnRemove": audioLibraryOnRemove,
  "AudioLibrary.OnScanFinished": audioLibraryOnScanFinished,
  "AudioLibrary.OnScanStarted": audioLibraryOnScanStarted,
  "AudioLibrary.OnUpdate": audioLibraryOnUpdate,
  "GUI.OnDPMSActivated": guiOnDPMSActivated,
  "GUI.OnDPMSDeactivated": guiOnDPMSDeactivated,
  "GUI.OnScreensaverActivated": guiOnScreensaverActivated,
  "GUI.OnScreensaverDeactivated": guiOnScreensaverDeactivated,
  "Input.OnInputFinished": inputOnInputFinished,
  "Input.OnInputRequested": inputOnInputRequested,
  "Player.OnAVChange": playerOnAVChange,
  "Player.OnPause": playerOnPause,
  "Player.OnPlay": playerOnPlay,
  "Player.OnPropertyChanged": playerOnPropertyChanged,
  "Player.OnResume": playerOnResume,
  "Player.OnSeek": playerOnSeek,
  "Player.OnSpeedChanged": playerOnSpeedChanged,
  "Player.OnStop": playerOnStop,
  "Playlist.OnAdd": playlistOnAdd,
  "Playlist.OnClear": playlistOnClear,
  "Playlist.OnRemove": playlistOnRemove,
  "System.OnLowBattery": systemOnLowBattery,
  "System.OnQuit": systemOnQuit,
  "System.OnRestart": systemOnRestart,
  "System.OnSleep": systemOnSleep,
  "System.OnWake": systemOnWake,
  "VideoLibrary.OnCleanFinished": videoLibraryOnCleanFinished,
  "VideoLibrary.OnCleanStarted": videoLibraryOnCleanStarted,
  "VideoLibrary.OnExport": videoLibraryOnExport,
  "VideoLibrary.OnRefresh": videoLibraryOnRefresh,
  "VideoLibrary.Library.OnRemove": videoLibraryOnRemove,
  "VideoLibrary.OnScanFinished": videoLibraryOnScanFinished,
  "VideoLibrary.OnScanStarted": videoLibraryOnScanStarted,
  "VideoLibrary.OnUpdate": videoLibraryOnUpdate,
};

export type NotificationMap = typeof notificationMap;
export type RequestResponseMap = typeof requestResponseMap;
